language: node_js
node_js:
  - "6"
script:
  - npm run lint
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: qRCjE5Qg9jZOd7pbvW48OnK0GUR9hAZwYjwxv0vekVlAro0p1CGS/7IBULn45aEuA77wGCnzvuPrjJBfAfQCaMwm+Avil5Zg0cXcHxXekVhdlklfmELViuQ+A1AYSvqAa11GVe14bE52pdTe2Fdou5ntjgq7j5qle+RNiPGTuBDKv3y2UW0amJjJZIHDx5cBMprpGZTW2XFUdbZac9YB4ImhU9X2m1LUa3vxCs/aqbOmeW1cEWRdWea5001tvwVnSLEWb68odqN9oAoF/N44FBVC0V05bDRsg/hyP6tsXjFTuaQlRmgT2kxeQOacrMviNYy0NFJc5oyfgE3hUcFkg+F/rPOPP4D+OWb41MG0hPQaJVvsiLI8GFa5aafVPYOZ71eo709DWM8cmiZPunf36EseE8gGWSOfbdtGREA6zkwLjUrI77FX17ddcVODtrzEn4iD9+xtxL1Hb6hHh6Figsqoy6Uf8y4NhkoTXoPBQhbyfHYgW46v6k+xufJiHYD2TN3i5QPm8PVg95NE36JLq/DmLHpXukz7BtYq2lGOn9jjCzfWS/i6yqRgFj8hwgp2TH9zPXiLihv24KZMs8d9xBpg11eICH3uhu2Q7S3S4yg8HxXCgVbnPttKqHDLIBxlMfVzkz+2cMaUV5t42trXCtqI85+WoMZddGI8qGQzxns=
